/**
 * Doppia recipe seed — tech (product mode), 7 templates. v2.
 * 통합 스키마 v1 (docs/TEMPLATE_STRUCTURE.md: A2 layered + A5 shot-list). recipes 테이블에 INSERT.
 *
 * v2 변경사항:
 *   - Spec Callout Grid: text_overlay:true 추가, look.negative에서 'text'/'logo' 제거, meta.render_notes 추가
 *     (SAFETY_NEGATIVE 충돌 방지 — 모델이 clean callout zone만 렌더링하고 텍스트 오버레이는 결정론적 레이어로 처리)
 *   - In-hand Quick Demo (신규): 2-shot partial-hand demo reel, ◈4, meta.flags=['experimental']
 *     (in-hand framing 도입 — partial/cropped hand로 AI-risk 최소화)
 *   - Tech Unbox ASMR: 이름 전역 고유화 (구 'Unbox ASMR Reel' — jewelry.v2와 충돌 → vertical 접두).
 *
 * v2 검증·확정 (2026-06-10): 7개 keep 확정. Quick Hero Snap(1샷 ◈2 진입 릴) add 후보는 보류
 *   — 기존 In-hand Quick Demo가 이미 ◈4 싼 릴스 티어를 채워 influencer/fashion/home/pet와 동일,
 *     강제 결손 아님. 가격 사다리 I2 I2 I2 I2 · R4 R6 R6 (위반 0) 그대로 확정.
 */
module.exports = [
  {
    "mode": "product",
    "vertical": "tech",
    "category": "Hero",
    "name": "Void Hero Cut",
    "output_type": "image_set",
    "credit_cost": 2,
    "sort_order": 1,
    "rationale": "The default e-commerce hero — a clean, dramatic catalog cut that any gadget seller drops straight onto a PDP or ad as the lead image.",
    "config": {
      "schema_version": 1,
      "mode": "product",
      "output": {
        "type": "image_set",
        "count": 4,
        "aspect_ratio": "4:5"
      },
      "subject": {
        "type": "product",
        "reference_strategy": "product_composite",
        "min_refs": 1
      },
      "look": {
        "style_preset": "Studio",
        "attributes": [
          "lighting:single_key_softbox_with_rim",
          "color:near_black_void",
          "texture:matte_seamless_floor",
          "context:infinite_dark_background"
        ],
        "extra_positive": "CRITICAL: identical product across all 4 shots, locked geometry, no morph or shape/size drift between angles, identical to the reference product (same exact color, finish, materials, proportions, port and button layout and branding placement), no invented parts or added logos. 100mm macro lens, f8 deep focus, premium tech product hero shot on seamless matte-black infinity cove, dramatic single softbox key from upper left, subtle cool rim light defining edges, controlled specular highlights on aluminum and glass, soft contact shadow grounding the device, color-accurate, crisp product silhouette, glossy gadget-launch advertising look.",
        "extra_negative": "warped product geometry, melted or rounded edges, duplicated ports, extra or missing buttons, distorted brand label, wrong proportions, harsh blown specular highlights, dusty smudged surface, fingerprints, busy distracting background, reflections of the camera or photographer, plastic CGI toy look, color shift on the device"
      },
      "shot_strategy": "list",
      "shots": [
        {
          "scene": "infinite matte-black studio void, soft contact shadow beneath",
          "pose": "front-on hero angle, device perfectly upright and centered",
          "composition": "medium_shot"
        },
        {
          "scene": "dark seamless cove with cool rim light raking the edge",
          "pose": "three-quarter angle showing face and side profile, slight low camera for stature",
          "composition": "medium_shot"
        },
        {
          "scene": "black void with a single tight specular highlight band",
          "pose": "floating slightly above surface, dramatic levitation hero",
          "composition": "medium_shot"
        },
        {
          "scene": "dark backdrop with faint gradient glow behind the device",
          "pose": "back/side three-quarter showing ports and detailing",
          "composition": "closeup"
        }
      ],
      "provider": {
        "image": "nano-banana",
        "video": "kling"
      }
    }
  },
  {
    "mode": "product",
    "vertical": "tech",
    "category": "Feature",
    "name": "Spec Callout Grid",
    "output_type": "image_set",
    "credit_cost": 2,
    "sort_order": 2,
    "rationale": "Sellers and Amazon/marketplace listers use this to turn one device into clean feature-callout panels that slot into infographic listings. Text callouts are applied as a deterministic overlay layer post-render — not baked in by the AI model.",
    "meta": {
      "render_notes": "Model renders the product + clean empty callout zones only (product offset in frame, generous negative space on the open side). NO text is generated by the AI. After render, a deterministic spec-callout text-overlay layer draws leader lines, spec labels, and headline copy into the reserved negative-space zones. Keep 'text' and 'logo' OUT of look.extra_negative to avoid SAFETY_NEGATIVE interference with the overlay pipeline."
    },
    "text_overlay": true,
    "config": {
      "schema_version": 1,
      "mode": "product",
      "output": {
        "type": "image_set",
        "count": 4,
        "aspect_ratio": "4:5"
      },
      "subject": {
        "type": "product",
        "reference_strategy": "product_composite",
        "min_refs": 1
      },
      "look": {
        "style_preset": "Studio",
        "attributes": [
          "lighting:bright_even_softbox_array",
          "color:cool_neutral_white",
          "texture:clean_seamless",
          "context:minimal_infographic_negative_space"
        ],
        "extra_positive": "CRITICAL: identical product across all shots, locked geometry, no morph or shape/size drift, consistent angle family from frame to frame, 85mm lens at f9, crisp edge-to-edge definition, bright even diffused key with broad soft fill and gentle rim separation over a smooth gradient backdrop, device isolated on a generous negative-space panel with a clean uncluttered empty margin reserved for composited spec callouts, true-to-spec rendering of metal, glass and matte surfaces, identical to the reference product (same exact color, finish, materials, proportions, port/button layout and branding placement), no invented parts or added logos, calm tech-catalog mood",
        "extra_negative": "warped geometry, extra or duplicated ports or buttons, distorted proportions, cluttered background intruding into the callout zone, harsh shadows, plastic CGI toy finish, lens flare, leader-line arrows touching or overlapping the product, callout zone filled or obstructed, blown specular highlights"
      },
      "shot_strategy": "list",
      "shots": [
        {
          "scene": "bright soft-gradient backdrop, large empty area to the right for callouts",
          "pose": "device front-on, offset left in frame leaving negative space",
          "composition": "medium_shot"
        },
        {
          "scene": "clean light-grey panel with even fill light",
          "pose": "three-quarter angle highlighting the control surface and buttons",
          "composition": "medium_shot"
        },
        {
          "scene": "minimal white seamless, top area open for headline callout",
          "pose": "slight top-down tilt emphasizing the top face of the device",
          "composition": "medium_shot"
        },
        {
          "scene": "soft cool backdrop with directional separation light",
          "pose": "detail framing on the port/charging area for a feature panel",
          "composition": "closeup"
        }
      ],
      "provider": {
        "image": "nano-banana",
        "video": "kling"
      }
    }
  },
  {
    "mode": "product",
    "vertical": "tech",
    "category": "Macro",
    "name": "Macro Tactile Zoom",
    "output_type": "image_set",
    "credit_cost": 2,
    "sort_order": 3,
    "rationale": "Premium-detail buyers (audio, wearables, accessories) use this to sell build quality — textures, machining, weave and finish at extreme close range.",
    "config": {
      "schema_version": 1,
      "mode": "product",
      "output": {
        "type": "image_set",
        "count": 4,
        "aspect_ratio": "4:5"
      },
      "subject": {
        "type": "product",
        "reference_strategy": "product_composite",
        "min_refs": 1
      },
      "look": {
        "style_preset": "Macro",
        "attributes": [
          "lighting:raking_grazing_light",
          "color:rich_contrast",
          "texture:micro_surface_detail",
          "context:dark_intimate_macro_set"
        ],
        "extra_positive": "CRITICAL: identical product across all shots, locked geometry, no morph or shape/size drift, extreme macro tactile detail of the device, raking grazing light revealing micro-texture, brushed aluminum grain, anodized finish, mesh weave, soft-touch coating, fine engraving and seams, 100mm macro lens at f4 with razor-thin focus and creamy bokeh falloff, focus-stacked detail on the hero edge, texture, finish and material identical to the reference product (same exact color, anodizing, grain direction, port and button layout and branding placement), no invented parts or added logos, luxurious tech-craftsmanship mood",
        "extra_negative": "soft mushy detail, out-of-focus hero subject, warped surface, fake or invented textures, repeating pattern artifacts, dust and lint, fingerprints, color noise, oversharpening halos, plastic CGI toy look, duplicated seams, smeared micro-detail, blown specular hotspots"
      },
      "shot_strategy": "list",
      "shots": [
        {
          "scene": "dark macro set, single grazing light across the surface",
          "pose": "extreme closeup on the brushed metal / finish texture",
          "composition": "closeup"
        },
        {
          "scene": "intimate low-key macro with soft falloff",
          "pose": "closeup on a physical button, dial or crown showing machining",
          "composition": "closeup"
        },
        {
          "scene": "macro set with cool rim accent",
          "pose": "closeup on speaker mesh / sensor / weave detail",
          "composition": "closeup"
        },
        {
          "scene": "dark backdrop, shallow-focus macro",
          "pose": "closeup on a logo-free engraved edge / chamfer / seam",
          "composition": "closeup"
        }
      ],
      "provider": {
        "image": "nano-banana",
        "video": "kling"
      }
    }
  },
  {
    "mode": "product",
    "vertical": "tech",
    "category": "Lifestyle",
    "name": "Desk Setup Flatlay",
    "output_type": "image_set",
    "credit_cost": 2,
    "sort_order": 4,
    "rationale": "Lifestyle/UGC-style listing shots — places the gadget in an aspirational desk scene so creators and DTC brands sell the vibe, not just the spec sheet.",
    "config": {
      "schema_version": 1,
      "mode": "product",
      "output": {
        "type": "image_set",
        "count": 4,
        "aspect_ratio": "4:5"
      },
      "subject": {
        "type": "product",
        "reference_strategy": "product_composite",
        "min_refs": 1
      },
      "look": {
        "style_preset": "Lifestyle",
        "attributes": [
          "lighting:soft_window_daylight",
          "color:warm_neutral_tone",
          "texture:wood_and_linen",
          "context:minimal_creative_desk"
        ],
        "extra_positive": "CRITICAL: identical product across all 4 shots, locked geometry, no morph or shape/size drift, device as the unambiguous hero. Shot on 35mm at f2.8, focus locked on the device, tack-sharp against gently blurred surroundings. Soft window daylight as key, low-contrast fill, faint rim along the device edge. Minimal desk flatlay on warm walnut with linen texture, small plant and notebook kept subordinate to the device. Identical to the reference product (same exact color, finish, materials, proportions, port/button layout and branding placement), no invented parts or added logos. Warm neutral, cozy work-from-home mood, tidy negative space.",
        "extra_negative": "warped product, duplicated devices, cluttered messy desk, distracting bright props competing with the product, plastic CGI toy finish, blown-out overexposed window, harsh shadows, tangled extra cables, color cast on the device, off-scale or wrong-proportion props, product lost in the busy scene"
      },
      "shot_strategy": "list",
      "shots": [
        {
          "scene": "top-down walnut desk flatlay with plant, notebook and coffee",
          "pose": "product centered as hero among tidy props, top-down",
          "composition": "full_body"
        },
        {
          "scene": "desk corner near a bright window, soft daylight",
          "pose": "product placed in use-context at a 45-degree eye-level angle",
          "composition": "medium_shot"
        },
        {
          "scene": "minimal desk vignette with shallow background bokeh",
          "pose": "product in foreground, props softly blurred behind",
          "composition": "medium_shot"
        },
        {
          "scene": "styled desk surface with linen texture",
          "pose": "detail of product resting beside a single complementary prop",
          "composition": "closeup"
        }
      ],
      "provider": {
        "image": "nano-banana",
        "video": "kling"
      }
    }
  },
  {
    "mode": "product",
    "vertical": "tech",
    "category": "Reel",
    "name": "In-hand Quick Demo",
    "output_type": "reel",
    "credit_cost": 4,
    "sort_order": 5,
    "rationale": "2026 tech-creator standard — a short 2-shot in-hand demo reel showing the device being used. Partial/cropped hand framing minimizes AI hand-generation risk while delivering authentic usage context for Reels/TikTok. Cheap ◈4 entry reel for creators on a budget.",
    "meta": {
      "flags": ["experimental"],
      "ai_risk_note": "In-hand framing introduces hand/finger generation. Mitigated by: (1) partial-hand / wrist-only crop so full five-finger hand is never in frame, (2) hardened negative prompt blocking malformed hands. Flag 'experimental' retained until hand generation quality is validated in production."
    },
    "config": {
      "schema_version": 1,
      "mode": "product",
      "output": {
        "type": "reel",
        "count": 2,
        "aspect_ratio": "9:16"
      },
      "subject": {
        "type": "product",
        "reference_strategy": "product_composite",
        "min_refs": 1
      },
      "look": {
        "style_preset": "Lifestyle",
        "attributes": [
          "lighting:soft_ambient_daylight",
          "color:clean_neutral_warm",
          "texture:natural_skin_and_device",
          "context:casual_in-hand_use"
        ],
        "extra_positive": "CRITICAL: identical product across both shots, locked geometry, no morph or shape/size drift; identical to the reference (same exact color, finish, materials, proportions, port/button layout and branding placement), no invented parts or added logos; in-hand demo, partial-hand / wrist-entry framing, only the lower palm and thumb edge visible, any visible fingers well-formed and natural with no extra or fused digits, anatomically correct relaxed grip; 35mm at f/2.0, focus locked on device, slightly soft background; clean daylight, soft window key, gentle fill, subtle rim on the edge; crisp surface detail, creator-style vertical 9:16, effortless everyday mood",
        "extra_negative": "full hand with all five fingers in frame, six fingers, fused or webbed digits, floating disconnected hand, melting or warped fingers, unnatural grip, warped product geometry, duplicated devices, jittery shaky motion, plastic CGI toy look, cluttered background, blown highlights, product slipping out of frame"
      },
      "shot_strategy": "list",
      "shots": [
        {
          "scene": "clean daylight environment, partial wrist-entry from below frame",
          "pose": "hand entering from the bottom edge holding the device at a natural grip angle, product face visible and sharp",
          "composition": "medium_shot"
        },
        {
          "scene": "same casual environment, slight camera drift",
          "pose": "device tilted slightly to reveal a key feature surface, only thumb and palm edge visible at the grip",
          "composition": "closeup"
        }
      ],
      "reel": {
        "per_shot_motion": [
          "slow push-in as hand lifts device into frame from below",
          "gentle tilt reveal with shallow drift, product stays center-sharp"
        ],
        "duration_per_shot": 3,
        "transition": "cut",
        "music_mood": "lo-fi house, 95-110 BPM, mellow Rhodes keys with soft boom-bap drums and warm sub-bass, bright relaxed everyday energy, reference-track vibe of a modern creator-vlog background groove",
        "captions": "auto"
      },
      "provider": {
        "image": "nano-banana",
        "video": "kling"
      }
    }
  },
  {
    "mode": "product",
    "vertical": "tech",
    "category": "Reel",
    "name": "Tech Unbox ASMR",
    "output_type": "reel",
    "credit_cost": 6,
    "sort_order": 6,
    "rationale": "The scroll-stopping format for new-drop hype — a tactile unboxing reel that DTC tech brands run as the launch teaser on Reels/TikTok.",
    "config": {
      "schema_version": 1,
      "mode": "product",
      "output": {
        "type": "reel",
        "count": 3,
        "aspect_ratio": "9:16"
      },
      "subject": {
        "type": "product",
        "reference_strategy": "product_composite",
        "min_refs": 1
      },
      "look": {
        "style_preset": "Cinematic",
        "attributes": [
          "lighting:soft_directional_key_with_glow",
          "color:moody_premium_tone",
          "texture:premium_packaging_matte",
          "context:dark_tabletop_set"
        ],
        "extra_positive": "CRITICAL: identical product across all 3 shots, locked geometry, no morph or shape/size drift, 50mm lens at f/2.0, slow rack-focus pulling onto the device as it is unveiled, ASMR unboxing reel on a dark moody tabletop, soft directional key with subtle glow, faint rim edge-lighting the silhouette, gentle fill holding shadow detail, hands-free framing, matte packaging easing open to a satisfying reveal, device identical to the reference product (same exact color, finish, materials, proportions, port/button layout and branding placement), no invented parts or added logos, shallow depth, vertical 9:16, premium gadget launch teaser mood",
        "extra_negative": "warped product, duplicated devices, distorted geometry, jittery shaky motion, blown specular highlights, plastic CGI toy look, cluttered background, motion blur smearing the product, dull flat reveal, inconsistent product between frames, cheap-looking packaging"
      },
      "shot_strategy": "list",
      "shots": [
        {
          "scene": "closed matte premium box on a dark tabletop, single glow light",
          "pose": "sealed package front-on, anticipation framing",
          "composition": "closeup"
        },
        {
          "scene": "box lid lifting to reveal the device nested inside",
          "pose": "top-down lid-off reveal, device emerging from foam",
          "composition": "medium_shot"
        },
        {
          "scene": "device lifted out, hero glow on dark backdrop",
          "pose": "final device hero, slow turn into the light",
          "composition": "medium_shot"
        }
      ],
      "reel": {
        "per_shot_motion": [
          "slow push-in on the sealed box",
          "top-down lid lift with gentle parallax",
          "slow orbit reveal with light glint sweep"
        ],
        "duration_per_shot": 3,
        "transition": "cut",
        "music_mood": "genre: minimal ambient electronic with ASMR foley-forward layering; BPM: 70-85; instruments: soft sub-bass pads, muted synth swells, tactile foley (packaging crinkle, lid slide, button click, fabric brush) mixed front and center; energy: calm, hushed, anticipatory build to a single satisfying reveal accent; reference vibe: Apple product-teaser ASMR meets Tycho-style downtempo ambient",
        "captions": "auto"
      },
      "provider": {
        "image": "nano-banana",
        "video": "kling"
      }
    }
  },
  {
    "mode": "product",
    "vertical": "tech",
    "category": "Reel",
    "name": "360 Glow Spin",
    "output_type": "reel",
    "credit_cost": 6,
    "sort_order": 7,
    "rationale": "The all-angle proof shot — a glowing turntable spin that lets shoppers see every side, ideal as the PDP loop or paid-ad B-roll for any gadget.",
    "config": {
      "schema_version": 1,
      "mode": "product",
      "output": {
        "type": "reel",
        "count": 3,
        "aspect_ratio": "9:16"
      },
      "subject": {
        "type": "product",
        "reference_strategy": "product_composite",
        "min_refs": 1
      },
      "look": {
        "style_preset": "Studio",
        "attributes": [
          "lighting:rotating_rim_glow",
          "color:sleek_dark_gradient",
          "texture:glossy_reflective_finish",
          "context:reflective_turntable_void"
        ],
        "extra_positive": "CRITICAL: identical product across every frame of the spin, locked geometry, no morph or shape/size drift, consistent surface reflection through the rotation, shot on an 85mm macro lens at f/8 with deep edge-to-edge focus, 360-degree turntable product spin, sleek dark gradient void, rotating rim glow tracing the edges, key light raking the body with soft fill, glossy floor with a mirror reflection, controlled speculars sweeping as it turns, identical to the reference product (same exact color, finish, materials, proportions, port/button layout and branding placement), no invented parts or added logos, vertical 9:16, premium gadget-launch reveal",
        "extra_negative": "warped or morphing geometry, duplicated ports, the device changing shape or size between frames, distorted brand label, jittery wobble or off-axis spin, blown specular highlights, plastic CGI toy finish, cluttered background, motion blur smear, color shift, inconsistent or duplicated reflection, flickering between frames"
      },
      "shot_strategy": "list",
      "shots": [
        {
          "scene": "reflective turntable in a dark gradient void, rim glow on",
          "pose": "front face rotating into a three-quarter view",
          "composition": "medium_shot"
        },
        {
          "scene": "glossy floor with soft mirror reflection, sweeping highlight",
          "pose": "side profile continuing the smooth 360 rotation",
          "composition": "medium_shot"
        },
        {
          "scene": "dark void with rim light tracing the rear edge",
          "pose": "back and final return to front, completing the spin",
          "composition": "medium_shot"
        }
      ],
      "reel": {
        "per_shot_motion": [
          "smooth clockwise turntable rotation, locked camera",
          "continuous rotation with highlight glint sweeping across body",
          "completing rotation, slow push-in on the hero front face"
        ],
        "duration_per_shot": 3,
        "transition": "fade",
        "music_mood": "genre: sleek minimal electronic / deep tech-house; BPM: 110-120; instruments: clean four-on-the-floor kick, sub bass, muted plucks, airy synth pads, subtle metallic percussion ticks; energy: smooth, controlled, confident build; reference-track vibe: Apple/flagship-gadget launch reveal, Tycho-meets-Bonobo polish",
        "captions": "auto"
      },
      "provider": {
        "image": "nano-banana",
        "video": "kling"
      }
    }
  }
];
