/* ⚠️ AUTO-GENERATED — node scripts/build_bg_roster.js
 * Doppia 배경(씬) 로스터 v1 — on-model용 (40씬, 8카테고리).
 * scene/light = on-model 생성에 주입할 환경/조명. 프리뷰: scripts/generate_bg_images.js → public/img/backgrounds/<id>.jpg
 */
module.exports = [
  {
    "id": "bg-studio-1",
    "seq": "01",
    "name": "Shadow Play",
    "category": "Studio",
    "category_key": "studio",
    "scene": "a clean studio with a warm-grey seamless backdrop and soft venetian-blind shadow patterns across it",
    "light": "soft directional light casting defined shadow shapes",
    "mood": "minimal editorial",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a clean studio with a warm-grey seamless backdrop and soft venetian-blind shadow patterns across it, soft directional light casting defined shadow shapes, minimal editorial mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-studio-2",
    "seq": "02",
    "name": "Color Pop",
    "category": "Studio",
    "category_key": "studio",
    "scene": "a studio with a smooth solid soft-coral seamless backdrop",
    "light": "bright even softbox light",
    "mood": "minimal editorial",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a studio with a smooth solid soft-coral seamless backdrop, bright even softbox light, minimal editorial mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-studio-3",
    "seq": "03",
    "name": "Paper Sweep",
    "category": "Studio",
    "category_key": "studio",
    "scene": "a studio with an off-white paper cyclorama sweeping into the floor",
    "light": "soft graduated studio light",
    "mood": "minimal editorial",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a studio with an off-white paper cyclorama sweeping into the floor, soft graduated studio light, minimal editorial mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-studio-4",
    "seq": "04",
    "name": "Spotlight",
    "category": "Studio",
    "category_key": "studio",
    "scene": "a dark moody studio with a single pool of light and deep falloff",
    "light": "dramatic single hard spotlight",
    "mood": "minimal editorial",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a dark moody studio with a single pool of light and deep falloff, dramatic single hard spotlight, minimal editorial mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-studio-5",
    "seq": "05",
    "name": "Gradient Dusk",
    "category": "Studio",
    "category_key": "studio",
    "scene": "a studio with a smooth blue-to-blush gradient backdrop",
    "light": "soft even light with a subtle glow",
    "mood": "minimal editorial",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a studio with a smooth blue-to-blush gradient backdrop, soft even light with a subtle glow, minimal editorial mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-home-1",
    "seq": "06",
    "name": "Sunlit Loft",
    "category": "Home / Lifestyle",
    "category_key": "home",
    "scene": "a bright minimalist loft apartment with warm wood floors and tall industrial windows",
    "light": "warm daylight streaming through the windows",
    "mood": "warm lived-in",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a bright minimalist loft apartment with warm wood floors and tall industrial windows, warm daylight streaming through the windows, warm lived-in mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-home-2",
    "seq": "07",
    "name": "Reading Nook",
    "category": "Home / Lifestyle",
    "category_key": "home",
    "scene": "a cozy reading nook with a linen armchair, a full bookshelf and a soft floor lamp",
    "light": "warm low ambient lamp light",
    "mood": "warm lived-in",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a cozy reading nook with a linen armchair, a full bookshelf and a soft floor lamp, warm low ambient lamp light, warm lived-in mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-home-3",
    "seq": "08",
    "name": "Scandi Living",
    "category": "Home / Lifestyle",
    "category_key": "home",
    "scene": "a neutral Scandinavian living room with pale wood, soft textiles and a few plants",
    "light": "soft diffused overcast daylight",
    "mood": "warm lived-in",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a neutral Scandinavian living room with pale wood, soft textiles and a few plants, soft diffused overcast daylight, warm lived-in mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-home-4",
    "seq": "09",
    "name": "Morning Kitchen",
    "category": "Home / Lifestyle",
    "category_key": "home",
    "scene": "a bright modern kitchen with a white marble counter and matte cabinetry",
    "light": "clean cool morning daylight",
    "mood": "warm lived-in",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a bright modern kitchen with a white marble counter and matte cabinetry, clean cool morning daylight, warm lived-in mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-home-5",
    "seq": "10",
    "name": "Linen Bedroom",
    "category": "Home / Lifestyle",
    "category_key": "home",
    "scene": "a serene bedroom with soft linen bedding and sheer white curtains",
    "light": "gentle backlit morning light through the curtains",
    "mood": "warm lived-in",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a serene bedroom with soft linen bedding and sheer white curtains, gentle backlit morning light through the curtains, warm lived-in mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-venue-1",
    "seq": "11",
    "name": "Corner Cafe",
    "category": "Cafe / Retail / Venue",
    "category_key": "venue",
    "scene": "a cozy corner cafe interior with a marble table, warm wood and soft background bokeh",
    "light": "warm tungsten ambient light",
    "mood": "refined ambient",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a cozy corner cafe interior with a marble table, warm wood and soft background bokeh, warm tungsten ambient light, refined ambient mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-venue-2",
    "seq": "12",
    "name": "Concept Boutique",
    "category": "Cafe / Retail / Venue",
    "category_key": "venue",
    "scene": "a minimalist concept boutique with softly blurred clothing racks and pale walls",
    "light": "clean even retail lighting",
    "mood": "refined ambient",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a minimalist concept boutique with softly blurred clothing racks and pale walls, clean even retail lighting, refined ambient mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-venue-3",
    "seq": "13",
    "name": "Art Gallery",
    "category": "Cafe / Retail / Venue",
    "category_key": "venue",
    "scene": "a bright white-walled art gallery with a light oak floor",
    "light": "soft even gallery light",
    "mood": "refined ambient",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a bright white-walled art gallery with a light oak floor, soft even gallery light, refined ambient mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-venue-4",
    "seq": "14",
    "name": "Hotel Lobby",
    "category": "Cafe / Retail / Venue",
    "category_key": "venue",
    "scene": "a luxe hotel lobby with marble, brass accents and low velvet seating",
    "light": "warm layered ambient light",
    "mood": "refined ambient",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a luxe hotel lobby with marble, brass accents and low velvet seating, warm layered ambient light, refined ambient mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-venue-5",
    "seq": "15",
    "name": "Old Bookstore",
    "category": "Cafe / Retail / Venue",
    "category_key": "venue",
    "scene": "a vintage bookstore with warm wooden shelves stacked with books",
    "light": "warm cozy interior light",
    "mood": "refined ambient",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a vintage bookstore with warm wooden shelves stacked with books, warm cozy interior light, refined ambient mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-urban-1",
    "seq": "16",
    "name": "City Street",
    "category": "Urban / Street",
    "category_key": "urban",
    "scene": "a daytime city sidewalk with softly blurred storefronts behind",
    "light": "bright natural overcast daylight",
    "mood": "candid street",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a daytime city sidewalk with softly blurred storefronts behind, bright natural overcast daylight, candid street mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-urban-2",
    "seq": "17",
    "name": "Shaded Alley",
    "category": "Urban / Street",
    "category_key": "urban",
    "scene": "a narrow European alley with cobblestones and weathered walls",
    "light": "soft shaded ambient light",
    "mood": "candid street",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a narrow European alley with cobblestones and weathered walls, soft shaded ambient light, candid street mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-urban-3",
    "seq": "18",
    "name": "Rooftop View",
    "category": "Urban / Street",
    "category_key": "urban",
    "scene": "an urban rooftop with a hazy city skyline behind",
    "light": "warm golden-hour light",
    "mood": "candid street",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, an urban rooftop with a hazy city skyline behind, warm golden-hour light, candid street mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-urban-4",
    "seq": "19",
    "name": "Crosswalk",
    "category": "Urban / Street",
    "category_key": "urban",
    "scene": "a busy urban crosswalk with motion-blurred traffic behind",
    "light": "crisp daylight",
    "mood": "candid street",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a busy urban crosswalk with motion-blurred traffic behind, crisp daylight, candid street mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-urban-5",
    "seq": "20",
    "name": "Subway Platform",
    "category": "Urban / Street",
    "category_key": "urban",
    "scene": "a clean modern subway platform with tiled walls",
    "light": "cool even fluorescent light",
    "mood": "candid street",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a clean modern subway platform with tiled walls, cool even fluorescent light, candid street mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-architectural-1",
    "seq": "21",
    "name": "Concrete Minimal",
    "category": "Architectural / Minimal",
    "category_key": "architectural",
    "scene": "a raw brutalist concrete wall with clean negative space",
    "light": "hard directional light with crisp shadow",
    "mood": "sculptural minimal",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a raw brutalist concrete wall with clean negative space, hard directional light with crisp shadow, sculptural minimal mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-architectural-2",
    "seq": "22",
    "name": "Marble Hall",
    "category": "Architectural / Minimal",
    "category_key": "architectural",
    "scene": "a grand marble hall with tall columns",
    "light": "soft diffused daylight from high windows",
    "mood": "sculptural minimal",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a grand marble hall with tall columns, soft diffused daylight from high windows, sculptural minimal mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-architectural-3",
    "seq": "23",
    "name": "Spiral Staircase",
    "category": "Architectural / Minimal",
    "category_key": "architectural",
    "scene": "a sculptural white spiral staircase",
    "light": "bright soft architectural light",
    "mood": "sculptural minimal",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a sculptural white spiral staircase, bright soft architectural light, sculptural minimal mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-architectural-4",
    "seq": "24",
    "name": "Arched Corridor",
    "category": "Architectural / Minimal",
    "category_key": "architectural",
    "scene": "a sunlit arched colonnade with warm stone",
    "light": "warm raking sunlight through the arches",
    "mood": "sculptural minimal",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a sunlit arched colonnade with warm stone, warm raking sunlight through the arches, sculptural minimal mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-architectural-5",
    "seq": "25",
    "name": "Glass Atrium",
    "category": "Architectural / Minimal",
    "category_key": "architectural",
    "scene": "a modern glass atrium with clean lines and greenery",
    "light": "bright airy natural light",
    "mood": "sculptural minimal",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a modern glass atrium with clean lines and greenery, bright airy natural light, sculptural minimal mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-nature-1",
    "seq": "26",
    "name": "Garden Green",
    "category": "Nature / Outdoor",
    "category_key": "nature",
    "scene": "a lush green garden with soft foliage",
    "light": "soft dappled daylight",
    "mood": "natural fresh",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a lush green garden with soft foliage, soft dappled daylight, natural fresh mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-nature-2",
    "seq": "27",
    "name": "Forest Path",
    "category": "Nature / Outdoor",
    "category_key": "nature",
    "scene": "a quiet forest path with tall trees",
    "light": "dappled light filtering through leaves",
    "mood": "natural fresh",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a quiet forest path with tall trees, dappled light filtering through leaves, natural fresh mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-nature-3",
    "seq": "28",
    "name": "Wild Meadow",
    "category": "Nature / Outdoor",
    "category_key": "nature",
    "scene": "an open meadow of tall grass swaying",
    "light": "soft breezy afternoon light",
    "mood": "natural fresh",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, an open meadow of tall grass swaying, soft breezy afternoon light, natural fresh mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-nature-4",
    "seq": "29",
    "name": "Coastal Cliff",
    "category": "Nature / Outdoor",
    "category_key": "nature",
    "scene": "a Mediterranean coastal cliff with deep blue sea behind",
    "light": "bright coastal sunlight",
    "mood": "natural fresh",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a Mediterranean coastal cliff with deep blue sea behind, bright coastal sunlight, natural fresh mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-nature-5",
    "seq": "30",
    "name": "Autumn Park",
    "category": "Nature / Outdoor",
    "category_key": "nature",
    "scene": "a park path covered in golden autumn leaves",
    "light": "warm soft autumn light",
    "mood": "natural fresh",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a park path covered in golden autumn leaves, warm soft autumn light, natural fresh mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-golden-1",
    "seq": "31",
    "name": "Golden Field",
    "category": "Golden / Editorial Light",
    "category_key": "golden",
    "scene": "a golden-hour wheat field stretching to the horizon",
    "light": "warm backlit golden-hour glow",
    "mood": "cinematic",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a golden-hour wheat field stretching to the horizon, warm backlit golden-hour glow, cinematic mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-golden-2",
    "seq": "32",
    "name": "Sunset Terrace",
    "category": "Golden / Editorial Light",
    "category_key": "golden",
    "scene": "a warm rooftop terrace at sunset",
    "light": "soft orange sunset light",
    "mood": "cinematic",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a warm rooftop terrace at sunset, soft orange sunset light, cinematic mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-golden-3",
    "seq": "33",
    "name": "Backlit Window",
    "category": "Golden / Editorial Light",
    "category_key": "golden",
    "scene": "a room with a large bright window behind the subject",
    "light": "strong backlight creating a soft rim",
    "mood": "cinematic",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a room with a large bright window behind the subject, strong backlight creating a soft rim, cinematic mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-golden-4",
    "seq": "34",
    "name": "Neon Night",
    "category": "Golden / Editorial Light",
    "category_key": "golden",
    "scene": "a moody city street at night with colorful neon signage",
    "light": "mixed neon and streetlight glow",
    "mood": "cinematic",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a moody city street at night with colorful neon signage, mixed neon and streetlight glow, cinematic mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-golden-5",
    "seq": "35",
    "name": "Poolside",
    "category": "Golden / Editorial Light",
    "category_key": "golden",
    "scene": "a bright poolside with turquoise water and clean loungers",
    "light": "high-key summer sunlight",
    "mood": "cinematic",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a bright poolside with turquoise water and clean loungers, high-key summer sunlight, cinematic mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-seasonal-1",
    "seq": "36",
    "name": "Snowy Street",
    "category": "Seasonal / Mood",
    "category_key": "seasonal",
    "scene": "a quiet snow-covered street with soft falling snow",
    "light": "soft cool overcast winter light",
    "mood": "atmospheric",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a quiet snow-covered street with soft falling snow, soft cool overcast winter light, atmospheric mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-seasonal-2",
    "seq": "37",
    "name": "Rainy Window",
    "category": "Seasonal / Mood",
    "category_key": "seasonal",
    "scene": "indoors beside a rain-streaked window",
    "light": "soft moody diffused daylight",
    "mood": "atmospheric",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, indoors beside a rain-streaked window, soft moody diffused daylight, atmospheric mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-seasonal-3",
    "seq": "38",
    "name": "Spring Blossom",
    "category": "Seasonal / Mood",
    "category_key": "seasonal",
    "scene": "under blooming cherry-blossom trees",
    "light": "soft pastel spring light",
    "mood": "atmospheric",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, under blooming cherry-blossom trees, soft pastel spring light, atmospheric mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-seasonal-4",
    "seq": "39",
    "name": "Tropical Palm",
    "category": "Seasonal / Mood",
    "category_key": "seasonal",
    "scene": "a bright tropical setting with palm leaves",
    "light": "vivid warm tropical sunlight",
    "mood": "atmospheric",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, a bright tropical setting with palm leaves, vivid warm tropical sunlight, atmospheric mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  },
  {
    "id": "bg-seasonal-5",
    "seq": "40",
    "name": "Desert Dune",
    "category": "Seasonal / Mood",
    "category_key": "seasonal",
    "scene": "warm minimal desert dunes under a clear sky",
    "light": "warm directional desert light",
    "mood": "atmospheric",
    "preview_prompt": "full-body fashion lookbook photograph of a fashion model wearing plain neutral basics, warm minimal desert dunes under a clear sky, warm directional desert light, atmospheric mood, natural realistic editorial photography, sharp focus on the model, full body in frame, shot on 50mm f/2.8, professional fashion photo",
    "negative": "distorted face, deformed or extra fingers, malformed hands, warped anatomy, oversaturated, cluttered composition, text, logos, watermark, low resolution, cropped head"
  }
];
